package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/scnon/zero-server/apps/merchant/api/graph"
	"github.com/scnon/zero-server/apps/merchant/api/model"
	"github.com/scnon/zero-server/models"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.SysUser, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.SysRole, error) {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
