package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/scnon/zero-server/apps/merchant/api/graph"
	"github.com/scnon/zero-server/apps/merchant/api/model"
	"github.com/scnon/zero-server/models"
)

// ID is the resolver for the id field.
func (r *sysUserResolver) ID(ctx context.Context, obj *models.SysUser) (string, error) {
	id := obj.ID
	return fmt.Sprintf("%d", id), nil
}

// Roles is the resolver for the roles field.
func (r *sysUserResolver) Roles(ctx context.Context, obj *models.SysUser) ([]*model.SysRole, error) {
	return []*model.SysRole{}, nil
}

// SysUser returns graph.SysUserResolver implementation.
func (r *Resolver) SysUser() graph.SysUserResolver { return &sysUserResolver{r} }

type sysUserResolver struct{ *Resolver }
