// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type SysRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
