// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ErrorInfo struct {
	Message string `json:"message"`
}

type QueryReq struct {
	Query         string `json:"query"`
	OperationName string `json:"operationName"`
}

type QueryResp struct {
	Errors ErrorInfo   `json:"errors,omitempty"`
	Data   interface{} `json:"data,omitempty"`
}
